# prometheus:
#   enabled: true
#   prometheusSpec:
#     # podMonitorNamespaceSelector:
#     #   any: true
#     podMonitorSelector: {}
#     podMonitorSelectorNilUsesHelmValues: false
#     # ruleNamespaceSelector:
#     #   any: true
#     ruleSelector: {}
#     ruleSelectorNilUsesHelmValues: false
#     # serviceMonitorNamespaceSelector:
#     #   any: true
#     serviceMonitorSelector: {}
#     serviceMonitorSelectorNilUsesHelmValues: false


